### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int32
b: <class 'torch.Tensor'>, torch.int32
c: <class 'torch.Tensor'>, torch.int32
d: <class 'numpy.ndarray'>, int32


### Function 1 - 增減維度

In [5]:
# Example 1 - 透過 squeeze減少維度、unqueeze增加維度
a = torch.tensor([[[1, 2, 3], [3, 4, 5]], [[5, 6, 7], [7, 8, 9]]])
print(a.shape, a)

b = torch.unsqueeze(a, dim=1)
print(b.shape, b)

c = torch.squeeze(b)
print(c.shape, c)

torch.Size([2, 2, 3]) tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])
torch.Size([2, 1, 2, 3]) tensor([[[[1, 2, 3],
          [3, 4, 5]]],


        [[[5, 6, 7],
          [7, 8, 9]]]])
torch.Size([2, 2, 3]) tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])


In [10]:
# Example 2 - 若所有的維度都不能再降維(一個維度裡有超過兩項就不能降)，做squeeze也不會有改變
a = torch.tensor([[[1, 2], [3, 3], [4, 5]], [[5, 6], [7, 7], [8, 9]]])
print(a.shape, a)

b = torch.unsqueeze(a, dim=2)
print(b.shape, b)

c = torch.squeeze(b)
print(c.shape, c)

c2 = torch.squeeze(c)
print(c2.shape, c2)

torch.Size([2, 3, 2]) tensor([[[1, 2],
         [3, 3],
         [4, 5]],

        [[5, 6],
         [7, 7],
         [8, 9]]])
torch.Size([2, 3, 1, 2]) tensor([[[[1, 2]],

         [[3, 3]],

         [[4, 5]]],


        [[[5, 6]],

         [[7, 7]],

         [[8, 9]]]])
torch.Size([2, 3, 2]) tensor([[[1, 2],
         [3, 3],
         [4, 5]],

        [[5, 6],
         [7, 7],
         [8, 9]]])
torch.Size([2, 3, 2]) tensor([[[1, 2],
         [3, 3],
         [4, 5]],

        [[5, 6],
         [7, 7],
         [8, 9]]])


### Function 2 - 改變形狀

In [9]:
# Example 1 - 利用reshape或view改變tensor的形狀
d = a.reshape(2, 6)
print(d.shape, d)

e = a.view(2, -1)
print(e.shape, e)

torch.Size([2, 6]) tensor([[1, 2, 3, 3, 4, 5],
        [5, 6, 7, 7, 8, 9]])
torch.Size([2, 6]) tensor([[1, 2, 3, 3, 4, 5],
        [5, 6, 7, 7, 8, 9]])


In [8]:
# Example 2 - ### your explanation ###


### Function 3 - 置換維度

In [12]:
# Example 1 - 利用transpose(要互換的兩個維度), permute(重新調整順序)兩種方法來置換矩陣的維度
f = a.transpose(1, 2)
print(f.shape, f)

g = a.permute(0, 2, 1)
print(g.shape, g)

torch.Size([2, 2, 3]) tensor([[[1, 3, 4],
         [2, 3, 5]],

        [[5, 7, 8],
         [6, 7, 9]]])
torch.Size([2, 2, 3]) tensor([[[1, 3, 4],
         [2, 3, 5]],

        [[5, 7, 8],
         [6, 7, 9]]])


In [10]:
# Example 2 - ### your explanation ###
### your code ###

### Function 4 - 矩陣乘法

In [14]:
# Example 1 - 利用.mm, .matmul, @ 等方法來做矩陣乘法 --> @和.matmul都不能互換矩陣位置，.mm無法乘vector

a = torch.randn((2,3))
b = torch.randn(3)
print(a.shape, b.shape)
a, b

torch.Size([2, 3]) torch.Size([3])


(tensor([[-1.2774, -0.8411, -0.0207],
         [ 1.1539,  0.5200,  0.0356]]), tensor([-0.6491, -0.3089, -0.1250]))

In [16]:
a@b

tensor([ 1.0916, -0.9141])

In [17]:
b@a

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 2x3)

In [18]:
a.mm(b)

RuntimeError: mat2 must be a matrix

In [19]:
b.mm(a)

RuntimeError: self must be a matrix

In [20]:
a.matmul(b)

tensor([ 1.0916, -0.9141])

In [21]:
b.matmul(a)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 2x3)

In [12]:
# Example 2 - ### your explanation ###
### your code ###